
package Programa;

import Controle.ControleFuncionario;
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Adryann
 */
public class CadastroFuncionarios extends javax.swing.JFrame {
    private final ControleFuncionario controle;
    /**
     * Creates new form CadastroFuncionarios
     */
    public CadastroFuncionarios() {
        initComponents();
        this.controle = new ControleFuncionario(this);
        this.controle.atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeFuncio = new javax.swing.JTextField();
        jTextFieldCPFFuncio = new javax.swing.JTextField();
        jTextFieldIdadeFuncio = new javax.swing.JTextField();
        jTextFieldContFuncio = new javax.swing.JTextField();
        jTextFieldContaFuncio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCargoFuncio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldSalarioFuncio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3443 = new javax.swing.JLabel();
        jTextFieldFuncionarioSexo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jlabel = new javax.swing.JLabel();
        jLabelFuncionarioEndereco = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPesquisarFuncionarioNome = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPesquisarFuncionarioCPF = new javax.swing.JTextField();
        jButtonPesquisarFuncionarios = new javax.swing.JButton();
        jButtonDeletarFuncionarioDT = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 50, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Idade:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 160, 50, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cadastro de Funcionários");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, -10, 510, 80);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Conta:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 100, 50, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("CPF:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 70, 40, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Contato:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 100, 60, 20);
        getContentPane().add(jTextFieldNomeFuncio);
        jTextFieldNomeFuncio.setBounds(60, 70, 240, 20);

        jTextFieldCPFFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFFuncioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCPFFuncio);
        jTextFieldCPFFuncio.setBounds(340, 70, 190, 20);

        jTextFieldIdadeFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdadeFuncioActionPerformed(evt);
            }
        });
        jTextFieldIdadeFuncio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldIdadeFuncioKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldIdadeFuncio);
        jTextFieldIdadeFuncio.setBounds(60, 160, 40, 20);
        getContentPane().add(jTextFieldContFuncio);
        jTextFieldContFuncio.setBounds(80, 100, 160, 20);

        jTextFieldContaFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContaFuncioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldContaFuncio);
        jTextFieldContaFuncio.setBounds(290, 100, 130, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cargo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 130, 60, 20);

        jTextFieldCargoFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCargoFuncioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCargoFuncio);
        jTextFieldCargoFuncio.setBounds(60, 130, 130, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Salario:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(430, 100, 60, 20);

        jTextFieldSalarioFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalarioFuncioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSalarioFuncio);
        jTextFieldSalarioFuncio.setBounds(480, 100, 80, 20);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Novo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 200, 90, 23);

        jLabel3443.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3443.setText("Sexo:");
        getContentPane().add(jLabel3443);
        jLabel3443.setBounds(160, 160, 40, 20);

        jTextFieldFuncionarioSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFuncionarioSexoActionPerformed(evt);
            }
        });
        jTextFieldFuncionarioSexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFuncionarioSexoKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldFuncionarioSexo);
        jTextFieldFuncionarioSexo.setBounds(210, 160, 90, 20);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(51, 255, 0));
        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 200, 90, 23);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(470, 200, 90, 23);

        jlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel.setText("Endereço:");
        getContentPane().add(jlabel);
        jlabel.setBounds(200, 130, 80, 20);
        getContentPane().add(jLabelFuncionarioEndereco);
        jLabelFuncionarioEndereco.setBounds(270, 130, 300, 20);

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Contato", "Cargo", "Idade", "Salario", "Conta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFuncionarios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 330, 660, 150);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Pesquisar:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 230, 110, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Nome:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 260, 60, 17);

        jTextFieldPesquisarFuncionarioNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarFuncionarioNomeActionPerformed(evt);
            }
        });
        jTextFieldPesquisarFuncionarioNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarFuncionarioNomeKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisarFuncionarioNome);
        jTextFieldPesquisarFuncionarioNome.setBounds(70, 260, 240, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("OU CPF:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(310, 260, 70, 20);

        jTextFieldPesquisarFuncionarioCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarFuncionarioCPFKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisarFuncionarioCPF);
        jTextFieldPesquisarFuncionarioCPF.setBounds(370, 260, 190, 20);

        jButtonPesquisarFuncionarios.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPesquisarFuncionarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPesquisarFuncionarios.setForeground(new java.awt.Color(51, 255, 0));
        jButtonPesquisarFuncionarios.setText("Pesquisar");
        jButtonPesquisarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarFuncionariosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisarFuncionarios);
        jButtonPesquisarFuncionarios.setBounds(290, 300, 110, 20);

        jButtonDeletarFuncionarioDT.setBackground(new java.awt.Color(0, 0, 0));
        jButtonDeletarFuncionarioDT.setForeground(new java.awt.Color(255, 0, 51));
        jButtonDeletarFuncionarioDT.setText("Deletar");
        jButtonDeletarFuncionarioDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarFuncionarioDTActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeletarFuncionarioDT);
        jButtonDeletarFuncionarioDT.setBounds(450, 300, 110, 23);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/canais-em-hd-que-ainda-nao-existem-e1471894627145.jpg"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 700, 490);

        setSize(new java.awt.Dimension(683, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCPFFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFFuncioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFFuncioActionPerformed

    private void jTextFieldIdadeFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdadeFuncioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdadeFuncioActionPerformed

    private void jTextFieldContaFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContaFuncioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContaFuncioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Voltar para tela principal
        TelaPrincipal tela = new TelaPrincipal();
                  tela.setVisible(true);
                     dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldFuncionarioSexoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioSexoKeyPressed
        // usar o enter para criar o cadastro
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
         cadastrar();
    }//GEN-LAST:event_jTextFieldFuncionarioSexoKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //limpar dados botão novo
        this.controle.novo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldSalarioFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalarioFuncioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalarioFuncioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Salvar novos funcionarios
        cadastrar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldFuncionarioSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncionarioSexoActionPerformed

    private void jTextFieldIdadeFuncioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdadeFuncioKeyPressed
         // usar o enter para criar o cadastro
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
         cadastrar();
    }//GEN-LAST:event_jTextFieldIdadeFuncioKeyPressed

    private void jTextFieldCargoFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCargoFuncioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCargoFuncioActionPerformed

    private void jTextFieldPesquisarFuncionarioNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarFuncionarioNomeKeyPressed
        // ao precionar enter execuar a função
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        pesquisarPorFuncionarios();
    }//GEN-LAST:event_jTextFieldPesquisarFuncionarioNomeKeyPressed

    private void jTextFieldPesquisarFuncionarioCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarFuncionarioCPFKeyPressed
        // ao precionar enter execuar a função
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        pesquisarPorFuncionarios();
    }//GEN-LAST:event_jTextFieldPesquisarFuncionarioCPFKeyPressed

    private void jButtonPesquisarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarFuncionariosActionPerformed
        //Pesquisar por um cliente
        pesquisarPorFuncionarios();
    }//GEN-LAST:event_jButtonPesquisarFuncionariosActionPerformed

    private void jButtonDeletarFuncionarioDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarFuncionarioDTActionPerformed
        // deletar deletar cliente
        this.controle.deletarFuncionario();
    }//GEN-LAST:event_jButtonDeletarFuncionarioDTActionPerformed

    private void jTextFieldPesquisarFuncionarioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarFuncionarioNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarFuncionarioNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonDeletarFuncionarioDT;
    private javax.swing.JButton jButtonPesquisarFuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3443;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLabelFuncionarioEndereco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JTextField jTextFieldCPFFuncio;
    private javax.swing.JTextField jTextFieldCargoFuncio;
    private javax.swing.JTextField jTextFieldContFuncio;
    private javax.swing.JTextField jTextFieldContaFuncio;
    private javax.swing.JTextField jTextFieldFuncionarioSexo;
    private javax.swing.JTextField jTextFieldIdadeFuncio;
    private javax.swing.JTextField jTextFieldNomeFuncio;
    private javax.swing.JTextField jTextFieldPesquisarFuncionarioCPF;
    private javax.swing.JTextField jTextFieldPesquisarFuncionarioNome;
    private javax.swing.JTextField jTextFieldSalarioFuncio;
    private javax.swing.JLabel jlabel;
    // End of variables declaration//GEN-END:variables

    private void cadastrar() {
         //Cadastro de funcionarios
        if(!"".equals(this.jTextFieldNomeFuncio.getText()) && !"".equals(this.jTextFieldCargoFuncio.getText()) && !"".equals(this.jTextFieldCPFFuncio.getText())){
        this.controle.salvar();
       
     }else{
       exibeMensagem("Está faltando algum dado!!");  
     } }
//exibir mensagens no sistema
    public void exibeMensagem(String mensagem) {
     JOptionPane.showMessageDialog(this, mensagem);
    }

    public JTextField getjTextFieldPesquisarFuncionarioCPF() {
        return jTextFieldPesquisarFuncionarioCPF;
    }

    public void setjTextFieldPesquisarFuncionarioCPF(JTextField jTextFieldPesquisarFuncionarioCPF) {
        this.jTextFieldPesquisarFuncionarioCPF = jTextFieldPesquisarFuncionarioCPF;
    }

    public JTextField getjTextFieldPesquisarFuncionarioNome() {
        return jTextFieldPesquisarFuncionarioNome;
    }

    public void setjTextFieldPesquisarFuncionarioNome(JTextField jTextFieldPesquisarFuncionarioNome) {
        this.jTextFieldPesquisarFuncionarioNome = jTextFieldPesquisarFuncionarioNome;
    }
    
    
    public JTextField getjTextFieldSalarioFuncio() {
        return jTextFieldSalarioFuncio;
    }

    public void setjTextFieldSalarioFuncio(JTextField jTextFieldSalarioFuncio) {
        this.jTextFieldSalarioFuncio = jTextFieldSalarioFuncio;
    }

    public JTextField getjLabelFuncionarioEndereco() {
        return jLabelFuncionarioEndereco;
    }

    public void setjLabelFuncionarioEndereco(JTextField jLabelFuncionarioEndereco) {
        this.jLabelFuncionarioEndereco = jLabelFuncionarioEndereco;
    }

    public JTable getjTableFuncionarios() {
        return jTableFuncionarios;
    }

    public void setjTableFuncionarios(JTable jTableFuncionarios) {
        this.jTableFuncionarios = jTableFuncionarios;
    }

    public JTextField getjTextFieldCPFFuncio() {
        return jTextFieldCPFFuncio;
    }

    public void setjTextFieldCPFFuncio(JTextField jTextFieldCPFFuncio) {
        this.jTextFieldCPFFuncio = jTextFieldCPFFuncio;
    }

    public JTextField getjTextFieldCargoFuncio() {
        return jTextFieldCargoFuncio;
    }

    public void setjTextFieldCargoFuncio(JTextField jTextFieldCargoFuncio) {
        this.jTextFieldCargoFuncio = jTextFieldCargoFuncio;
    }

    public JTextField getjTextFieldContFuncio() {
        return jTextFieldContFuncio;
    }

    public void setjTextFieldContFuncio(JTextField jTextFieldContFuncio) {
        this.jTextFieldContFuncio = jTextFieldContFuncio;
    }

    public JTextField getjTextFieldContaFuncio() {
        return jTextFieldContaFuncio;
    }

    public void setjTextFieldContaFuncio(JTextField jTextFieldContaFuncio) {
        this.jTextFieldContaFuncio = jTextFieldContaFuncio;
    }

    public JTextField getjTextFieldFuncionarioSexo() {
        return jTextFieldFuncionarioSexo;
    }

    public void setjTextFieldFuncionarioSexo(JTextField jTextFieldFuncionarioSexo) {
        this.jTextFieldFuncionarioSexo = jTextFieldFuncionarioSexo;
    }

    public JTextField getjTextFieldIdadeFuncio() {
        return jTextFieldIdadeFuncio;
    }

    public void setjTextFieldIdadeFuncio(JTextField jTextFieldIdadeFuncio) {
        this.jTextFieldIdadeFuncio = jTextFieldIdadeFuncio;
    }

    public JTextField getjTextFieldNomeFuncio() {
        return jTextFieldNomeFuncio;
    }

    public void setjTextFieldNomeFuncio(JTextField jTextFieldNomeFuncio) {
        this.jTextFieldNomeFuncio = jTextFieldNomeFuncio;
    }

    private void pesquisarPorFuncionarios() {
      if(!"".equals(this.jTextFieldPesquisarFuncionarioNome.getText()) || 
              !"".equals(this.jTextFieldPesquisarFuncionarioCPF.getText())){
        this.controle.buscarFuncionario();
     }else{
       exibeMensagem("Dados incompletos!!");  
     }
    }
    
    }
