/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programa;

/**
 *
 * @author Adryann
 */
public class CadastroFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFuncionarios
     */
    public CadastroFuncionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeFuncio = new javax.swing.JTextField();
        jTextFieldCPFFuncio = new javax.swing.JTextField();
        jTextFieldIdadeFuncio = new javax.swing.JTextField();
        jTextFieldContFuncio = new javax.swing.JTextField();
        jTextFieldContaFuncio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCargoFuncio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldSalarioFuncio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();

        jTextField6.setText("jTextField6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 90, 50, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Idade:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 190, 50, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cadastro de Funcionários");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 510, 80);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Conta:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 150, 50, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("CPF:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 110, 40, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Contato:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 130, 60, 20);
        getContentPane().add(jTextFieldNomeFuncio);
        jTextFieldNomeFuncio.setBounds(60, 90, 240, 20);

        jTextFieldCPFFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFFuncioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCPFFuncio);
        jTextFieldCPFFuncio.setBounds(50, 110, 190, 20);

        jTextFieldIdadeFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdadeFuncioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdadeFuncio);
        jTextFieldIdadeFuncio.setBounds(60, 190, 40, 20);
        getContentPane().add(jTextFieldContFuncio);
        jTextFieldContFuncio.setBounds(80, 130, 160, 20);

        jTextFieldContaFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContaFuncioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldContaFuncio);
        jTextFieldContaFuncio.setBounds(60, 150, 130, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cargo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 170, 60, 20);
        getContentPane().add(jTextFieldCargoFuncio);
        jTextFieldCargoFuncio.setBounds(60, 170, 130, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Salario:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 210, 60, 20);
        getContentPane().add(jTextFieldSalarioFuncio);
        jTextFieldSalarioFuncio.setBounds(70, 210, 80, 20);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Novo");
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 250, 90, 23);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(51, 255, 0));
        jButton2.setText("Salvar");
        getContentPane().add(jButton2);
        jButton2.setBounds(70, 250, 90, 23);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(360, 250, 90, 23);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FundoFuncio.jpg"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 510, 370);

        setSize(new java.awt.Dimension(516, 397));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCPFFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFFuncioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFFuncioActionPerformed

    private void jTextFieldIdadeFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdadeFuncioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdadeFuncioActionPerformed

    private void jTextFieldContaFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContaFuncioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContaFuncioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Voltar para tela principal
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldCPFFuncio;
    private javax.swing.JTextField jTextFieldCargoFuncio;
    private javax.swing.JTextField jTextFieldContFuncio;
    private javax.swing.JTextField jTextFieldContaFuncio;
    private javax.swing.JTextField jTextFieldIdadeFuncio;
    private javax.swing.JTextField jTextFieldNomeFuncio;
    private javax.swing.JTextField jTextFieldSalarioFuncio;
    // End of variables declaration//GEN-END:variables
}
