package Programa;

import Controle.ControleCCliente;
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
/**
 *
 * @author Adryann
 */
public class CadastroCliente extends javax.swing.JFrame {

    private final ControleCCliente controle;
    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
        this.controle = new ControleCCliente(this);
        this.controle.atualizaTabela();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jTextFieldCPFCliente = new javax.swing.JTextField();
        jTextFieldContatoCliente = new javax.swing.JTextField();
        IdadeCliente = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldClienteSexo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPesquisarClienteNome = new javax.swing.JTextField();
        jTextFieldPesquisarClienteCPF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        FundoCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro  de Clientes");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 50, 60, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("CPF:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 80, 40, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Contato:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Idade:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 140, 40, 17);
        getContentPane().add(jTextFieldNomeCliente);
        jTextFieldNomeCliente.setBounds(80, 50, 260, 20);
        getContentPane().add(jTextFieldCPFCliente);
        jTextFieldCPFCliente.setBounds(80, 80, 170, 20);
        getContentPane().add(jTextFieldContatoCliente);
        jTextFieldContatoCliente.setBounds(80, 110, 120, 20);
        getContentPane().add(IdadeCliente);
        IdadeCliente.setBounds(80, 140, 40, 20);

        jButtonSalvar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonSalvar.setForeground(new java.awt.Color(51, 255, 0));
        jButtonSalvar.setText("Salvar");
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(40, 190, 80, 23);

        jButtonNovo.setBackground(new java.awt.Color(0, 0, 0));
        jButtonNovo.setForeground(new java.awt.Color(255, 51, 0));
        jButtonNovo.setText("Cancelar");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(285, 190, 90, 23);

        jButtonancelar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonancelar.setText("Novo");
        jButtonancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonancelar);
        jButtonancelar.setBounds(160, 190, 90, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Pesquisar:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 230, 110, 30);

        jTextFieldClienteSexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldClienteSexoKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldClienteSexo);
        jTextFieldClienteSexo.setBounds(170, 140, 140, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Sexo:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(130, 140, 50, 20);
        getContentPane().add(jTextFieldPesquisarClienteNome);
        jTextFieldPesquisarClienteNome.setBounds(60, 260, 240, 20);
        getContentPane().add(jTextFieldPesquisarClienteCPF);
        jTextFieldPesquisarClienteCPF.setBounds(360, 260, 190, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nome:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 260, 60, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText(" OU");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 260, 30, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("CPF:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 260, 50, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Pesquisar");
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 280, 130, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Contato", "Cpf", "Idade", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 310, 560, 350);

        FundoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Usuário.png"))); // NOI18N
        getContentPane().add(FundoCadastro);
        FundoCadastro.setBounds(-40, -130, 620, 670);

        setSize(new java.awt.Dimension(558, 465));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // Voltar para tela principal
         TelaPrincipal tela = new TelaPrincipal();
                      tela.setVisible(true);
                             dispose();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jTextFieldClienteSexoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldClienteSexoKeyPressed
        // 
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
         cadastrar(); 
    }//GEN-LAST:event_jTextFieldClienteSexoKeyPressed

    private void jButtonancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonancelarActionPerformed
        //limpar dados botão novo
        this.controle.novo();
    }//GEN-LAST:event_jButtonancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FundoCadastro;
    private javax.swing.JTextField IdadeCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCPFCliente;
    private javax.swing.JTextField jTextFieldClienteSexo;
    private javax.swing.JTextField jTextFieldContatoCliente;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldPesquisarClienteCPF;
    private javax.swing.JTextField jTextFieldPesquisarClienteNome;
    // End of variables declaration//GEN-END:variables
    
        public void cadastrar(){
         //Cadastro de clientes
        if(!"".equals(this.jTextFieldNomeCliente.getText()) && !"".equals(this.jTextFieldCPFCliente.getText()) && !"".equals(this.jTextFieldContatoCliente.getText())){
        this.controle.salvar();
     }else{
       exibeMensagem("Está faltando algum dado!!");  
     } 
        }
        
    //exibir mensagens no sistema
    public void exibeMensagem(String mensagem) {
     JOptionPane.showMessageDialog(this, mensagem);
    }
    
    public JTextField getIdadeCliente() {
        return IdadeCliente;
    }

    public void setIdadeCliente(JTextField IdadeCliente) {
        this.IdadeCliente = IdadeCliente;
    }

    public JTextField getjTextFieldCPFCliente() {
        return jTextFieldCPFCliente;
    }

    public void setjTextFieldCPFCliente(JTextField jTextFieldCPFCliente) {
        this.jTextFieldCPFCliente = jTextFieldCPFCliente;
    }

    public JTextField getjTextFieldClienteSexo() {
        return jTextFieldClienteSexo;
    }

    public void setjTextFieldClienteSexo(JTextField jTextFieldClienteSexo) {
        this.jTextFieldClienteSexo = jTextFieldClienteSexo;
    }

    public JTextField getjTextFieldContatoCliente() {
        return jTextFieldContatoCliente;
    }

    public void setjTextFieldContatoCliente(JTextField jTextFieldContatoCliente) {
        this.jTextFieldContatoCliente = jTextFieldContatoCliente;
    }

    public JTextField getjTextFieldNomeCliente() {
        return jTextFieldNomeCliente;
    }

    public void setjTextFieldNomeCliente(JTextField jTextFieldNomeCliente) {
        this.jTextFieldNomeCliente = jTextFieldNomeCliente;
    }

    public JTable getjTabelaClientes() {
        return jTable1;
    }

    public void setjTabelaClientes(JTable jTabelaClientes) {
        this.jTable1 = jTabelaClientes;
    }


}
